"""Export generators: TMX / CSV for the corpus, TBX / CSV for the termbase."""
from __future__ import annotations

import csv
import io
from datetime import datetime, timezone
from xml.sax.saxutils import escape


def _now_tmx() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")


def segments_to_csv(segments: list[dict], source_lang: str, target_lang: str) -> str:
    buf = io.StringIO()
    writer = csv.writer(buf, lineterminator="\n")
    writer.writerow([f"source ({source_lang})", f"target ({target_lang})", "status"])
    for seg in segments:
        writer.writerow([seg["sourceText"], seg["targetText"], seg.get("status", "auto")])
    return buf.getvalue()


def segments_to_tmx(segments: list[dict], source_lang: str, target_lang: str) -> str:
    date = _now_tmx()
    tus = []
    for seg in segments:
        src = seg["sourceText"].strip()
        tgt = seg["targetText"].strip()
        if not src and not tgt:
            continue
        tus.append(
            f'    <tu creationdate="{date}" creationid="TermExtrax">\n'
            f'      <tuv xml:lang="{escape(source_lang, {chr(34): "&quot;"})}">\n'
            f"        <seg>{escape(src)}</seg>\n"
            f"      </tuv>\n"
            f'      <tuv xml:lang="{escape(target_lang, {chr(34): "&quot;"})}">\n'
            f"        <seg>{escape(tgt)}</seg>\n"
            f"      </tuv>\n"
            f"    </tu>"
        )
    body = "\n".join(tus)
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<tmx version="1.4">\n'
        f'  <header creationtool="TermExtrax" creationtoolversion="1.0" datatype="plaintext"\n'
        f'          segtype="sentence" adminlang="en" srclang="{escape(source_lang, {chr(34): "&quot;"})}"\n'
        f'          o-tmf="TermExtrax" creationdate="{date}"/>\n'
        "  <body>\n"
        f"{body}\n"
        "  </body>\n"
        "</tmx>\n"
    )


def terms_to_csv(terms: list[dict], source_lang: str, target_lang: str) -> str:
    buf = io.StringIO()
    writer = csv.writer(buf, lineterminator="\n")
    writer.writerow([f"source term ({source_lang})", f"target term ({target_lang})", "frequency"])
    for term in terms:
        writer.writerow([term["sourceTerm"], term.get("targetTerm", ""), term.get("frequency", 0)])
    return buf.getvalue()


def terms_to_tbx(terms: list[dict], source_lang: str, target_lang: str) -> str:
    """TBX-Basic style dialect of the TermBase eXchange format."""
    entries = []
    for idx, term in enumerate(terms, start=1):
        src = term["sourceTerm"].strip()
        tgt = term.get("targetTerm", "").strip()
        if not src:
            continue
        tgt_block = ""
        if tgt:
            tgt_block = (
                f'        <langSec xml:lang="{escape(target_lang, {chr(34): "&quot;"})}">\n'
                "          <termSec>\n"
                f"            <term>{escape(tgt)}</term>\n"
                "          </termSec>\n"
                "        </langSec>\n"
            )
        entries.append(
            f'      <conceptEntry id="c{idx}">\n'
            f'        <langSec xml:lang="{escape(source_lang, {chr(34): "&quot;"})}">\n'
            "          <termSec>\n"
            f"            <term>{escape(src)}</term>\n"
            f'            <note>frequency: {int(term.get("frequency", 0))}</note>\n'
            "          </termSec>\n"
            "        </langSec>\n"
            f"{tgt_block}"
            "      </conceptEntry>"
        )
    body = "\n".join(entries)
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<tbx style="dca" type="TBX-Basic" xml:lang="en"\n'
        '     xmlns="urn:iso:std:iso:30042:ed-2">\n'
        "  <tbxHeader>\n"
        "    <fileDesc>\n"
        "      <titleStmt>\n"
        "        <title>TermExtrax termbase export</title>\n"
        "      </titleStmt>\n"
        "      <sourceDesc>\n"
        "        <p>Generated by TermExtrax</p>\n"
        "      </sourceDesc>\n"
        "    </fileDesc>\n"
        "  </tbxHeader>\n"
        "  <text>\n"
        "    <body>\n"
        f"{body}\n"
        "    </body>\n"
        "  </text>\n"
        "</tbx>\n"
    )
